apiVersion: v1
kind: Service
metadata:
  name: nexclipper-service
  labels: 
    app: nexclipper-service
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
  - port: 10180
    protocol: TCP
    targetPort: 9000
    name: http
    nodePort: 30003
  selector:  
    app: nexclipper-service

